apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-controller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ft.services
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress
          servicePort: 5050