apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-controller
spec:
  tls:
  - hosts:
    - ft.services
    secretName: ft.services-tls
  rules:
  - host: ft.services
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
