secretGenerator:
- name: mysql-database
  literals:
  - wordpress=wordpress
- name: mysql-secret
  literals:
  - root-password=42root
  - php-username=admin
  - php-password=42php
  - wp-username=wordpress
  - wp-password=42wp
- name: wordpress-phpmyadmin
  literals:
  - blowfish=,3Eet7Gu:O2VRV4GGSf0Wl8JI:iMXwEr
resources:
- ingress-controller.yaml
- mysql/deployment.yaml
- wordpress/deployment.yaml
- phpmyadmin/deployment.yaml