secretGenerator:
  - name: mysql-database
    literals:
      - wordpress=wordpress

  - name: mysql-secret
    literals:
      - root-password=42root

      - pma-username=admin
      - pma-password=42pma

      - wp-username=wordpress
      - wp-password=42wp

  - name: wordpress-secret
    literals:
      - admin-username=admin
      - admin-password=42wp
      - admin-email=admin@ft.services

      - author-username=author
      - author-password=42wpauthor
      - author-email=author@ft.services

      - editor-username=editor
      - editor-password=42wpeditor
      - editor-email=editor@ft.services

  - name: pma-secret
    literals:
      - blowfish=J]n8ZqRD8[NXAcJFpFxa6WE;v-Jx17}2

  - name: nginx-ssh-secret
    literals:
      - username=www-data
      - password=42nginx

  - name: ftps-secret
    literals:
      - username=admin
      - password=42ftps

  - name: influxdb-database
    namespace: monitoring
    literals:
      - monitoring=monitoring

  - name: influxdb-secret
    namespace: monitoring
    literals:
      - admin-username=admin
      - admin-password=42influx

      - telegraf-username=telegraf
      - telegraf-password=42telegraf
  
      - grafana-username=grafana
      - grafana-password=42grafana

  - name: grafana-secret
    namespace: monitoring
    literals:
      - username=admin
      - password=42grafana

resources:
  - rolebindings.yaml
  - influxdb/deployment.yaml
  - telegraf/deployment.yaml
  - grafana/deployment.yaml
  - mysql/deployment.yaml
  - wordpress/deployment.yaml
  - phpmyadmin/deployment.yaml
  - nginx/deployment.yaml
  - ftps/deployment.yaml
