apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: ft_services/mysql
        imagePullPolicy: Never
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      initContainers:
      - image: ft_services/mysql
        imagePullPolicy: Never
        name: init-mysql
        env:
        - name: MYSQL_WP_DB
          valueFrom:
            secretKeyRef:
              name: mysql-database
              key: wordpress
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_WP_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: wp-username
        - name: MYSQL_WP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: wp-password
        - name: MYSQL_PHP_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: php-username
        - name: MYSQL_PHP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: php-password
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        command: ['sh', 'init.sh']
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

