apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: database
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  volumeName: mysql-pv
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: database
    spec:
      containers:
      - image: ft_services/mysql
        imagePullPolicy: Never
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 8
      initContainers:
      - image: ft_services/mysql
        imagePullPolicy: Never
        name: init-mysql
        env:
        - name: MYSQL_WP_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-database
              key: wordpress
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_WP_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: wp-username
        - name: MYSQL_WP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: wp-password
        - name: MYSQL_PMA_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: pma-username
        - name: MYSQL_PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: pma-password
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        args: [""]
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
