apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: external
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
    - name: nginx
      protocol: TCP
      port: 80
    - name: nginx-tls
      protocol: TCP
      port: 443
    - name: ssh
      protocol: TCP
      port: 22
  selector:
    app: nginx
    tier: frontend
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - image: ft_services/nginx
        imagePullPolicy: Never
        name: nginx
        env:
          - name: SSH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nginx-ssh-secret
                key: password
        ports:
        - containerPort: 80
          name: nginx
        - containerPort: 443
          name: nginx-tls
        - containerPort: 22
          name: ssh
        volumeMounts:
        - name: tls
          mountPath: /etc/nginx/certs
          readOnly: true
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - /liveness.sh
          initialDelaySeconds: 45
          timeoutSeconds: 3
      volumes:
      - name: tls
        secret:
          secretName: default-tls
