apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: external
  name: phpmyadmin
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
    - name: phpmyadmin
      port: 5000
  selector:
    app: wordpress
    tier: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: phpmyadmin
    spec:
      containers:
      - image: ft_services/phpmyadmin
        imagePullPolicy: Never
        name: phpmyadmin
        ports:
        - containerPort: 5000
          name: phpmyadmin
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 8
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: PMA_BLOWFISH
          valueFrom:
            secretKeyRef:
              name: pma-secret
              key: blowfish
