apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: wordpress
spec:
  ports:
    - port: 5000
  selector:
    app: wordpress
    tier: frontend
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: ft_services/phpmyadmin
        imagePullPolicy: Never
        name: phpmyadmin
        env:
        - name: MYSQL_HOST
          value: mysql
        ports:
        - containerPort: 5000
          name: phpmyadmin