apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: monitoring
  name: telegraf
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      tier: telegraf
  template:
    metadata:
      labels:
        app: grafana
        tier: telegraf
    spec:
      serviceAccountName: metrics
      containers:
      - name: telegraf
        image: ft_services/telegraf
        imagePullPolicy: Never
        resources:
          limits:
            memory: "500Mi"
          requests:
            cpu: "500m"
            memory: "500Mi"
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: INFLUXDB_URL
            value: http://influxdb:8086
          - name: INFLUXDB_DATABASE
            valueFrom:
                secretKeyRef:
                  name: influxdb-database
                  key: monitoring
          - name: INFLUXDB_USERNAME
            valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: telegraf-username
          - name: INFLUXDB_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: telegraf-password
          - name: HOST_PROC
            value: /rootfs/proc
          - name: HOST_SYS
            value: /rootfs/sys
        volumeMounts:
          - name: sys
            mountPath: /rootfs/sys
            readOnly: true
          - name: docker
            mountPath: /var/run/docker.sock
            readOnly: true
          - name: proc
            mountPath: /rootfs/proc
            readOnly: true
          - name: utmp
            mountPath: /var/run/utmp
            readOnly: true
      volumes:
        - name: sys
          hostPath:
              path: /sys
        - name: docker
          hostPath:
              path: /var/run/docker.sock
        - name: proc
          hostPath:
              path: /proc
        - name: utmp
          hostPath:
              path: /var/run/utmp
