apiVersion: v1
kind: Service
metadata:
  name: ftp
  labels:
    app: ftps
spec:
  type: NodePort
  ports:
    - name: ftp-data
      port: 30020
      nodePort: 30020
    - name: ftp-cmd
      port: 21
      nodePort: 30021
  selector:
    app: ftps
    tier: ftp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ftp-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ftp"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: ftp-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftp-pv-claim
  labels:
    app: ftps
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: ftp-pv
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ftp
spec:
  selector:
    matchLabels:
      tier: ftp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: ftp
    spec:
      containers:
      - image: ft_services/ftps
        imagePullPolicy: Never
        name: ftps
        env:
        - name: FTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: ftp-secret
              key: username
        - name: FTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ftp-secret
              key: password
        ports:
        - name: ftp-data
          containerPort: 30020
        - name: ftp-cmd
          containerPort: 21
        volumeMounts:
        - name: ftp-persistent-storage
          mountPath: /var/ftp
        - name: ftp-tls
          mountPath: /etc/vsftpd/tls
          readOnly: true
      volumes:
      - name: ftp-persistent-storage
        persistentVolumeClaim:
          claimName: ftp-pv-claim
      - name: ftp-tls
        secret:
          secretName: ft.services-tls
