apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
    - name: ftps-cmd
      protocol: TCP
      port: 21
    - name: ftps-pasv-0
      protocol: TCP
      port: 1024
    - name: ftps-pasv-1
      protocol: TCP
      port: 1025
    - name: ftps-pasv-2
      protocol: TCP
      port: 1026
    - name: ftps-pasv-3
      protocol: TCP
      port: 1027
  selector:
    app: ftps
    tier: ftp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ftps-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ftp"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: ftps-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
  labels:
    app: ftps
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  volumeName: ftps-pv
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
      tier: ftp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
        tier: ftp
    spec:
      containers:
      - image: ft_services/ftps
        imagePullPolicy: Never
        name: ftps
        env:
        - name: FTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: ftps-secret
              key: username
        - name: FTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ftps-secret
              key: password
        ports:
        - name: ftps-cmd
          containerPort: 21
        - name: ftps-pasv-0
          containerPort: 1024
        - name: ftps-pasv-1
          containerPort: 1025
        - name: ftps-pasv-2
          containerPort: 1026
        - name: ftps-pasv-3
          containerPort: 1027
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /var/ftp
        - name: ftps-tls
          mountPath: /etc/vsftpd/tls
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 21
          initialDelaySeconds: 60
          periodSeconds: 20
          failureThreshold: 8
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
      - name: ftps-tls
        secret:
          secretName: default-tls
