apiVersion: v1
kind: Service
metadata:
  name: ftp
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
    - name: ftp-cmd
      protocol: TCP
      port: 21
    - name: ftp-pasv-0
      protocol: TCP
      port: 1024
    - name: ftp-pasv-1
      protocol: TCP
      port: 1025
    - name: ftp-pasv-2
      protocol: TCP
      port: 1026
    - name: ftp-pasv-3
      protocol: TCP
      port: 1027
  selector:
    app: ftps
    tier: ftp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ftp-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ftp"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: ftp-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftp-pv-claim
  labels:
    app: ftps
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: ftp-pv
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ftp
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
      tier: ftp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
        tier: ftp
    spec:
      containers:
      - image: ft_services/ftp
        imagePullPolicy: Never
        name: ftp
        env:
        - name: FTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: ftp-secret
              key: username
        - name: FTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ftp-secret
              key: password
        ports:
        - name: ftp-cmd
          containerPort: 21
        - name: ftp-pasv-0
          containerPort: 1024
        - name: ftp-pasv-1
          containerPort: 1025
        - name: ftp-pasv-2
          containerPort: 1026
        - name: ftp-pasv-3
          containerPort: 1027
        volumeMounts:
        - name: ftp-persistent-storage
          mountPath: /var/ftp
        - name: ftp-tls
          mountPath: /etc/vsftpd/tls
          readOnly: true
      volumes:
      - name: ftp-persistent-storage
        persistentVolumeClaim:
          claimName: ftp-pv-claim
      - name: ftp-tls
        secret:
          secretName: ft.services-tls
